name: Linting

on:
  push:
    branches: [ staging, master ]
  
  pull_request:
    branches: [ staging, master ]

jobs:
  linting:
    runs-on:  Ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Store cache
        uses: actions/cache@v2
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip

      - name: Install dependecies
        run: |
          python -m pip install black==19.10b0
          python -m pip install isort==4.3.21
          python -m pip install mypy==0.770
          
      - name: Format check
        run:  black --check .

      - name: Typing check
        run: mypy --strict ./neural_network_compression
      
      - name: Imports order check
        run: isort -c
